#!/bin/bash
# generate-checklists.sh
# Generates checklist files from spec.md
# Usage: ./generate-checklists.sh <feature-id>

FEATURE_ID=$1
SPEC_DIR="Sprints/Specs/${FEATURE_ID}"
CHECKLIST_DIR="${SPEC_DIR}/checklists"
DATE=$(date +%Y-%m-%d)

if [ -z "$FEATURE_ID" ]; then
    echo "Usage: $0 <feature-id>"
    echo "Example: $0 001-user-authentication"
    exit 1
fi

if [ ! -d "$SPEC_DIR" ]; then
    echo "Error: Spec directory not found: $SPEC_DIR"
    exit 1
fi

if [ ! -f "${SPEC_DIR}/spec.md" ]; then
    echo "Error: spec.md not found in $SPEC_DIR"
    exit 1
fi

# Create checklists directory
mkdir -p "$CHECKLIST_DIR"

echo "Generating checklists for feature: $FEATURE_ID"

# Generate Requirements Checklist
cat > "${CHECKLIST_DIR}/requirements.md" << REQEOF
# Requirements Checklist: ${FEATURE_ID}

**Date**: ${DATE}
**Status**: Pending

## Functional Requirements

| ID | Requirement | Implemented | Tested | Verified |
|----|-------------|-------------|--------|----------|
| FR1 | | [ ] | [ ] | [ ] |
| FR2 | | [ ] | [ ] | [ ] |

## Non-Functional Requirements

| ID | Requirement | Met | Evidence |
|----|-------------|-----|----------|
| NFR1 | | [ ] | |
| NFR2 | | [ ] | |

## User Stories

<!-- Copy acceptance criteria from spec.md -->

## Edge Cases

- [ ] Empty input handled
- [ ] Maximum limits tested
- [ ] Error states handled
- [ ] Concurrent access handled

## Summary

- Total Items: 0
- Passed: 0
- Failed: 0
- Status: PENDING

---
*Generated by generate-checklists.sh*
REQEOF

# Generate Design Checklist
cat > "${CHECKLIST_DIR}/design.md" << DESIGNEOF
# Design Checklist: ${FEATURE_ID}

**Date**: ${DATE}
**Status**: Pending

## Architecture

- [ ] Design follows existing patterns
- [ ] Component boundaries are clear
- [ ] Dependencies are minimized
- [ ] No circular dependencies introduced

## Data Model

- [ ] Entities properly normalized
- [ ] Relationships correctly defined
- [ ] Indexes planned for queries
- [ ] Migration strategy defined

## API Design

- [ ] RESTful conventions followed
- [ ] Consistent naming
- [ ] Proper HTTP methods used
- [ ] Error responses standardized
- [ ] Versioning considered

## Security

- [ ] Authentication required where needed
- [ ] Authorization checks in place
- [ ] Input validation implemented
- [ ] Sensitive data protected
- [ ] No secrets in code

## Performance

- [ ] Database queries optimized
- [ ] Caching strategy defined
- [ ] No N+1 query issues
- [ ] Pagination implemented for lists

## Maintainability

- [ ] Code is self-documenting
- [ ] Complex logic has comments
- [ ] Consistent code style
- [ ] No magic numbers/strings

## Summary

- Total Items: 22
- Passed: 0
- Failed: 0
- Status: PENDING

---
*Generated by generate-checklists.sh*
DESIGNEOF

# Generate Implementation Checklist
cat > "${CHECKLIST_DIR}/implementation.md" << IMPLEOF
# Implementation Checklist: ${FEATURE_ID}

**Date**: ${DATE}
**Status**: Pending

## Code Quality

- [ ] All tests passing
- [ ] No linting errors
- [ ] No type errors
- [ ] Code coverage acceptable (>80%)
- [ ] No debug statements left

## Testing

- [ ] Unit tests written
- [ ] Integration tests written
- [ ] Edge cases tested
- [ ] Error scenarios tested
- [ ] Tests are deterministic

## Documentation

- [ ] README updated (if needed)
- [ ] API documentation updated
- [ ] Code comments for complex logic
- [ ] CHANGELOG updated

## Git Hygiene

- [ ] Commits are atomic and well-described
- [ ] No merge conflicts
- [ ] Branch is up to date with main
- [ ] No unrelated changes included

## Pre-Deployment

- [ ] Environment variables documented
- [ ] Database migrations tested
- [ ] Rollback plan exists
- [ ] Feature flags configured (if applicable)

## Final Verification

- [ ] Manual testing completed
- [ ] Stakeholder demo done (if required)
- [ ] No known bugs remaining
- [ ] Ready for code review

## Summary

- Total Items: 22
- Passed: 0
- Failed: 0
- Status: PENDING

---
*Generated by generate-checklists.sh*
IMPLEOF

echo "Checklists generated in: $CHECKLIST_DIR"
echo "  - requirements.md"
echo "  - design.md"
echo "  - implementation.md"
echo ""
echo "Next steps:"
echo "  1. Review and customize checklists based on spec.md"
echo "  2. Fill in requirement details from spec"
echo "  3. Check items as you verify them"
