# generate-checklists.ps1
# Generates checklist files from spec.md
# Usage: .\generate-checklists.ps1 <feature-id>

param(
    [Parameter(Position=0)]
    [string]$FeatureId
)

$SpecDir = "Sprints/Specs/$FeatureId"
$ChecklistDir = "$SpecDir/checklists"
$Date = Get-Date -Format "yyyy-MM-dd"

if ([string]::IsNullOrEmpty($FeatureId)) {
    Write-Host "Usage: .\generate-checklists.ps1 <feature-id>"
    Write-Host "Example: .\generate-checklists.ps1 001-user-authentication"
    exit 1
}

if (-not (Test-Path $SpecDir)) {
    Write-Host "Error: Spec directory not found: $SpecDir"
    exit 1
}

if (-not (Test-Path "$SpecDir/spec.md")) {
    Write-Host "Error: spec.md not found in $SpecDir"
    exit 1
}

# Create checklists directory
if (-not (Test-Path $ChecklistDir)) {
    New-Item -ItemType Directory -Path $ChecklistDir -Force | Out-Null
}

Write-Host "Generating checklists for feature: $FeatureId"

# Generate Requirements Checklist
$RequirementsContent = @"
# Requirements Checklist: $FeatureId

**Date**: $Date
**Status**: Pending

## Functional Requirements

| ID | Requirement | Implemented | Tested | Verified |
|----|-------------|-------------|--------|----------|
| FR1 | | [ ] | [ ] | [ ] |
| FR2 | | [ ] | [ ] | [ ] |

## Non-Functional Requirements

| ID | Requirement | Met | Evidence |
|----|-------------|-----|----------|
| NFR1 | | [ ] | |
| NFR2 | | [ ] | |

## User Stories

<!-- Copy acceptance criteria from spec.md -->

## Edge Cases

- [ ] Empty input handled
- [ ] Maximum limits tested
- [ ] Error states handled
- [ ] Concurrent access handled

## Summary

- Total Items: 0
- Passed: 0
- Failed: 0
- Status: PENDING

---
*Generated by generate-checklists.ps1*
"@

Set-Content -Path "$ChecklistDir/requirements.md" -Value $RequirementsContent -Encoding UTF8

# Generate Design Checklist
$DesignContent = @"
# Design Checklist: $FeatureId

**Date**: $Date
**Status**: Pending

## Architecture

- [ ] Design follows existing patterns
- [ ] Component boundaries are clear
- [ ] Dependencies are minimized
- [ ] No circular dependencies introduced

## Data Model

- [ ] Entities properly normalized
- [ ] Relationships correctly defined
- [ ] Indexes planned for queries
- [ ] Migration strategy defined

## API Design

- [ ] RESTful conventions followed
- [ ] Consistent naming
- [ ] Proper HTTP methods used
- [ ] Error responses standardized
- [ ] Versioning considered

## Security

- [ ] Authentication required where needed
- [ ] Authorization checks in place
- [ ] Input validation implemented
- [ ] Sensitive data protected
- [ ] No secrets in code

## Performance

- [ ] Database queries optimized
- [ ] Caching strategy defined
- [ ] No N+1 query issues
- [ ] Pagination implemented for lists

## Maintainability

- [ ] Code is self-documenting
- [ ] Complex logic has comments
- [ ] Consistent code style
- [ ] No magic numbers/strings

## Summary

- Total Items: 22
- Passed: 0
- Failed: 0
- Status: PENDING

---
*Generated by generate-checklists.ps1*
"@

Set-Content -Path "$ChecklistDir/design.md" -Value $DesignContent -Encoding UTF8

# Generate Implementation Checklist
$ImplementationContent = @"
# Implementation Checklist: $FeatureId

**Date**: $Date
**Status**: Pending

## Code Quality

- [ ] All tests passing
- [ ] No linting errors
- [ ] No type errors
- [ ] Code coverage acceptable (>80%)
- [ ] No debug statements left

## Testing

- [ ] Unit tests written
- [ ] Integration tests written
- [ ] Edge cases tested
- [ ] Error scenarios tested
- [ ] Tests are deterministic

## Documentation

- [ ] README updated (if needed)
- [ ] API documentation updated
- [ ] Code comments for complex logic
- [ ] CHANGELOG updated

## Git Hygiene

- [ ] Commits are atomic and well-described
- [ ] No merge conflicts
- [ ] Branch is up to date with main
- [ ] No unrelated changes included

## Pre-Deployment

- [ ] Environment variables documented
- [ ] Database migrations tested
- [ ] Rollback plan exists
- [ ] Feature flags configured (if applicable)

## Final Verification

- [ ] Manual testing completed
- [ ] Stakeholder demo done (if required)
- [ ] No known bugs remaining
- [ ] Ready for code review

## Summary

- Total Items: 22
- Passed: 0
- Failed: 0
- Status: PENDING

---
*Generated by generate-checklists.ps1*
"@

Set-Content -Path "$ChecklistDir/implementation.md" -Value $ImplementationContent -Encoding UTF8

Write-Host "Checklists generated in: $ChecklistDir"
Write-Host "  - requirements.md"
Write-Host "  - design.md"
Write-Host "  - implementation.md"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Review and customize checklists based on spec.md"
Write-Host "  2. Fill in requirement details from spec"
Write-Host "  3. Check items as you verify them"
